### ISSUE TITLE
Что за проект

### ISSUE THREAD

**Issue by Diaskhan** [vashkan/BPMN#1]
Извините можно вопрос.
 А что это за проект ??
Судя по всему какой то редактор BPMN ???

**Comment by vashkan** [comment]
Да, это часть графического редактора диаграмм бизнес процессов в нотации BPMN 2.0 написанный под фреймворк Mono.

**Comment by Diaskhan** [comment]
То есть получается под Винду не заведется ??

**Comment by vashkan** [comment]
Mono фреймворк кроссплатформенный, так что не исключено что может завестись.
http://www.mono-project.com
